/*
 * test_shannon.c — tests for the Shannon cipher, including real
 * ground-truth vectors from the actual reference implementation.
 *
 * HISTORY WORTH KEEPING: this file previously only did an internal
 * round-trip check (encrypt with one cipher instance, decrypt with
 * an independently-keyed-and-nonced second instance, check they
 * agree). That kind of test cannot catch a systematic bug applied
 * symmetrically to both encrypt and decrypt -- and that's exactly
 * what shipped for a while: sbox1/sbox2 used XOR where the reference
 * algorithm uses OR between two rotated terms (confirmed by tracing
 * Rust's actual operator precedence, not assumed), which changes the
 * entire keystream but leaves our own encrypt/decrypt symmetric with
 * each other, so this test suite kept passing throughout. It took a
 * live Spotify server rejecting real traffic to surface it.
 *
 * The vectors below close that gap: they were generated by installing
 * a real Rust toolchain, compiling the actual `shannon` crate
 * (unmodified, from the same source vendored for the C port), and
 * running it -- not read from source and reasoned about by hand,
 * which is exactly the process that missed the original bug twice
 * over. See apps/spotify-native/src/spotify/shannon.c's header for
 * the full incident writeup.
 */

#include <glib.h>
#include <stdio.h>
#include <string.h>
#include "shannon.h"

static void
hex_to_bytes (const gchar *hex, guint8 *out, gsize out_len)
{
  for (gsize i = 0; i < out_len; i++) {
    unsigned int byte;
    sscanf (hex + i * 2, "%02x", &byte);
    out[i] = (guint8) byte;
  }
}

static void
assert_hex_matches (const guint8 *buf, gsize len, const gchar *expected)
{
  gchar actual[512] = {0};
  gchar *p = actual;
  for (gsize i = 0; i < len; i++)
    p += sprintf (p, "%02x", buf[i]);
  g_assert_cmpstr (actual, ==, expected);
}

static void
test_key_setup_no_crash (void)
{
  ShannonCipher cipher;
  guint8 key[16] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
                    0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10};
  shannon_key_setup (&cipher, key, sizeof (key));
  g_assert_true (TRUE);
}

static void
test_internal_roundtrip (void)
{
  /* Still useful as a basic sanity check, but NOT sufficient alone --
   * see file header. Kept alongside the real vectors below, not
   * instead of them. */
  ShannonCipher enc, dec;
  guint8 key[16] = {0};
  guint8 nonce[8] = {0};

  shannon_key_setup (&enc, key, sizeof (key));
  shannon_nonce (&enc, nonce, sizeof (nonce));
  shannon_key_setup (&dec, key, sizeof (key));
  shannon_nonce (&dec, nonce, sizeof (nonce));

  guint8 plaintext[32];
  for (int i = 0; i < 32; i++) plaintext[i] = (guint8) i;

  guint8 buf[32];
  memcpy (buf, plaintext, sizeof (buf));

  shannon_encrypt (&enc, buf, sizeof (buf));
  g_assert_false (memcmp (buf, plaintext, sizeof (plaintext)) == 0);

  shannon_decrypt (&dec, buf, sizeof (buf));
  g_assert_cmpmem (buf, sizeof (buf), plaintext, sizeof (plaintext));
}

static void
test_vector_a (void)
{
  /* All-zero key/nonce, 32-byte sequential plaintext, exactly 8 whole words */
  guint8 key[16];
  hex_to_bytes ("00000000000000000000000000000000", key, 16);
  ShannonCipher c;
  shannon_key_setup (&c, key, 16);
  guint8 nonce[8];
  hex_to_bytes ("0000000000000000", nonce, 8);
  shannon_nonce (&c, nonce, 8);
  guint8 buf[32];
  hex_to_bytes ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", buf, 32);
  shannon_encrypt (&c, buf, 32);
  assert_hex_matches (buf, 32, "4f073b3c20dc97eee3d5430a98e679b216039a21f98f2f17ba9fa6ca5c15b340");
}

static void
test_vector_b (void)
{
  /* Non-word-aligned length (17 bytes), exercises the partial-word tail path */
  guint8 key[16];
  hex_to_bytes ("aabbccddeeff11223344556677889900", key, 16);
  ShannonCipher c;
  shannon_key_setup (&c, key, 16);
  guint8 nonce[4];
  hex_to_bytes ("01020304", nonce, 4);
  shannon_nonce (&c, nonce, 4);
  guint8 buf[17];
  hex_to_bytes ("7368616e6e6f6e2074657374206d736721", buf, 17);
  shannon_encrypt (&c, buf, 17);
  assert_hex_matches (buf, 17, "95ded11228f37c0a66ea85c59bcf2a3183");
  guint8 mac[4];
  shannon_finish (&c, mac, 4);
  assert_hex_matches (mac, 4, "c24e9931");
}

static void
test_vector_c (void)
{
  /* nonce_u32(0) path -- what ap.c actually uses for the first packet after a handshake */
  guint8 key[16];
  hex_to_bytes ("30313233343536373839616263646566", key, 16);
  ShannonCipher c;
  shannon_key_setup (&c, key, 16);
  shannon_nonce_u32 (&c, 0);
  guint8 buf[4];
  hex_to_bytes ("deadbeef", buf, 4);
  shannon_encrypt (&c, buf, 4);
  assert_hex_matches (buf, 4, "13524523");
  guint8 mac[4];
  shannon_finish (&c, mac, 4);
  assert_hex_matches (mac, 4, "009a7c51");
}

static void
test_vector_d (void)
{
  /* nonce_u32(5) -- a nonzero counter, matching real per-packet usage after several packets */
  guint8 key[16];
  hex_to_bytes ("66656463626139383736353433323130", key, 16);
  ShannonCipher c;
  shannon_key_setup (&c, key, 16);
  shannon_nonce_u32 (&c, 5);
  guint8 buf[20];
  hex_to_bytes ("000102030405060708090a0b0c0d0e0f10111213", buf, 20);
  shannon_encrypt (&c, buf, 20);
  assert_hex_matches (buf, 20, "ff6df67b6a5bfb9935544f1ab7b711797b4c43ec");
  guint8 mac[4];
  shannon_finish (&c, mac, 4);
  assert_hex_matches (mac, 4, "40370bcf");
}

int
main (int argc, char *argv[])
{
  g_test_init (&argc, &argv, NULL);
  g_test_add_func ("/shannon/key-setup-no-crash",  test_key_setup_no_crash);
  g_test_add_func ("/shannon/internal-roundtrip",  test_internal_roundtrip);
  g_test_add_func ("/shannon/real-vector-a-wholewords", test_vector_a);
  g_test_add_func ("/shannon/real-vector-b-partialword", test_vector_b);
  g_test_add_func ("/shannon/real-vector-c-nonce-u32-zero", test_vector_c);
  g_test_add_func ("/shannon/real-vector-d-nonce-u32-nonzero", test_vector_d);
  return g_test_run ();
}
